CREATE TABLE [dbo].[Contracts]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[TenantId] UNIQUEIDENTIFIER NOT NULL,
	[RoomId] UNIQUEIDENTIFIER NOT NULL,
	[AccrualTypeId] UNIQUEIDENTIFIER NOT NULL,
	[CalcCoefficientId] UNIQUEIDENTIFIER NOT NULL,
	[StartDate] DATE NOT NULL, 
    [EndDate] DATE NOT NULL, 
    CONSTRAINT [PK_Contracts] PRIMARY KEY CLUSTERED ([Id] ASC)
)
