CREATE TABLE [dbo].[Tenants]
(
	[Id] NVARCHAR(128) NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	[Address] NVARCHAR(MAX) NOT NULL, 
    [PhoneNumber] NVARCHAR(50) NULL, 
    CONSTRAINT [PK_Tenants] PRIMARY KEY CLUSTERED ([Id] ASC)
)
